from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol

from models import (
    AgentResult,
    Artifact,
    CriticProfile,
    CriticReview,
    DomainAssessment,
    ResearchResult,
    Source,
    StateTransition,
    Task,
    UserApproval,
    WorkflowRun,
)
from models.contracts import Claim


@dataclass(frozen=True)
class TaskAuditSnapshot:
    """Restart-safe persisted view of one task and its execution history."""

    task: Task
    workflow_run: WorkflowRun | None
    transitions: tuple[StateTransition, ...] = ()
    domain_assessments: tuple[DomainAssessment, ...] = ()
    critic_profiles: tuple[CriticProfile, ...] = ()
    user_approvals: tuple[UserApproval, ...] = ()
    agent_results: tuple[AgentResult, ...] = ()
    research_results: tuple[ResearchResult, ...] = ()
    claims: tuple[Claim, ...] = ()
    sources: tuple[Source, ...] = ()
    reviews: tuple[CriticReview, ...] = ()
    artifacts: tuple[Artifact, ...] = ()


class PersistenceStore(Protocol):
    """Storage boundary used by Supervisor without coupling agents to SQLite."""

    def save_task(self, task: Task) -> None: ...
    def save_workflow_run(self, workflow_run: WorkflowRun) -> None: ...
    def save_state_transition(self, transition: StateTransition) -> None: ...
    def save_agent_result(self, result: AgentResult) -> None: ...
    def save_domain_assessment(self, assessment: DomainAssessment) -> None: ...
    def save_critic_profile(self, profile: CriticProfile) -> None: ...
    def save_user_approval(self, approval: UserApproval) -> None: ...
    def save_research_result(self, result: ResearchResult) -> None: ...
    def save_claim(self, claim: Claim) -> None: ...
    def save_source(self, source: Source) -> None: ...
    def save_critic_review(self, review: CriticReview) -> None: ...
    def save_artifact(self, artifact: Artifact) -> None: ...

    def load_task(self, task_id: str) -> Task: ...
    def load_workflow_run(self, workflow_run_id: str) -> WorkflowRun: ...
    def load_workflow_for_task(self, task_id: str) -> WorkflowRun | None: ...
    def load_state_transitions(self, workflow_run_id: str) -> list[StateTransition]: ...
    def load_agent_results(self, task_id: str) -> list[AgentResult]: ...
    def load_domain_assessments(self, task_id: str) -> list[DomainAssessment]: ...
    def load_critic_profiles(self, task_id: str) -> list[CriticProfile]: ...
    def load_user_approvals(self, task_id: str) -> list[UserApproval]: ...
    def load_research_results(self, task_id: str) -> list[ResearchResult]: ...
    def load_claims(self, task_id: str) -> list[Claim]: ...
    def load_sources(self, task_id: str) -> list[Source]: ...
    def load_reviews(self, task_id: str) -> list[CriticReview]: ...
    def load_artifacts(self, task_id: str) -> list[Artifact]: ...
    def load_task_audit(self, task_id: str) -> TaskAuditSnapshot: ...
