from enum import StrEnum


class TaskStatus(StrEnum):
    NEW = "NEW"
    PROFILE_GENERATING = "PROFILE_GENERATING"
    PROFILE_REVIEW_REQUIRED = "PROFILE_REVIEW_REQUIRED"
    PROFILE_APPROVED = "PROFILE_APPROVED"
    RESEARCHING = "RESEARCHING"
    DRAFT_READY = "DRAFT_READY"
    REVIEWING = "REVIEWING"
    REVISE_REQUIRED = "REVISE_REQUIRED"
    APPROVED = "APPROVED"
    FINALIZING = "FINALIZING"
    FINALIZED = "FINALIZED"
    FAILED = "FAILED"
    MAX_ITERATIONS_REACHED = "MAX_ITERATIONS_REACHED"
    COMPLETED_WITH_LIMITATIONS = "COMPLETED_WITH_LIMITATIONS"


class WorkflowStatus(StrEnum):
    RUNNING = "RUNNING"
    WAITING_FOR_USER = "WAITING_FOR_USER"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    COMPLETED_WITH_LIMITATIONS = "COMPLETED_WITH_LIMITATIONS"


class WorkflowType(StrEnum):
    RESEARCH_CRITIC = "RESEARCH_CRITIC"


class ActorType(StrEnum):
    USER = "USER"
    SUPERVISOR = "SUPERVISOR"
    AGENT = "AGENT"
    SYSTEM = "SYSTEM"


class RiskLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ProfileStatus(StrEnum):
    DRAFT = "DRAFT"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"


class AgentType(StrEnum):
    RESEARCH = "RESEARCH"
    CRITIC = "CRITIC"
    REPORT_GENERATOR = "REPORT_GENERATOR"


class AgentStatus(StrEnum):
    ACTIVE = "ACTIVE"
    DISABLED = "DISABLED"
    DEPRECATED = "DEPRECATED"


class ExecutionStatus(StrEnum):
    SUCCEEDED = "SUCCEEDED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"


class ClaimType(StrEnum):
    FACT = "FACT"
    INTERPRETATION = "INTERPRETATION"
    INFERENCE = "INFERENCE"
    ESTIMATE = "ESTIMATE"
    RECOMMENDATION = "RECOMMENDATION"


class ImportanceLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class VerificationStatus(StrEnum):
    UNVERIFIED = "UNVERIFIED"
    PARTIALLY_VERIFIED = "PARTIALLY_VERIFIED"
    VERIFIED = "VERIFIED"
    CONTRADICTED = "CONTRADICTED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class SourceType(StrEnum):
    OFFICIAL = "OFFICIAL"
    PRIMARY_DOCUMENT = "PRIMARY_DOCUMENT"
    STANDARD = "STANDARD"
    PEER_REVIEWED = "PEER_REVIEWED"
    ACADEMIC = "ACADEMIC"
    GOVERNMENT = "GOVERNMENT"
    MANUFACTURER = "MANUFACTURER"
    NEWS = "NEWS"
    PROFESSIONAL_PUBLICATION = "PROFESSIONAL_PUBLICATION"
    REFERENCE = "REFERENCE"
    USER_PROVIDED = "USER_PROVIDED"
    OTHER = "OTHER"


class ReliabilityClass(StrEnum):
    A = "A"
    B = "B"
    C = "C"
    D = "D"


class ReviewDecision(StrEnum):
    PASS = "PASS"
    REVISE = "REVISE"


class ArtifactType(StrEnum):
    DRAFT_REPORT = "DRAFT_REPORT"
    FINAL_REPORT = "FINAL_REPORT"
    REVIEW_PROTOCOL = "REVIEW_PROTOCOL"


class ArtifactStatus(StrEnum):
    GENERATED = "GENERATED"
    APPROVED = "APPROVED"
    SUPERSEDED = "SUPERSEDED"
    FAILED = "FAILED"


class ErrorType(StrEnum):
    VALIDATION_ERROR = "VALIDATION_ERROR"
    TOOL_ERROR = "TOOL_ERROR"
    LLM_ERROR = "LLM_ERROR"
    TIMEOUT = "TIMEOUT"
    SOURCE_ERROR = "SOURCE_ERROR"
    CONTRACT_ERROR = "CONTRACT_ERROR"
    STATE_ERROR = "STATE_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class ApprovalType(StrEnum):
    CRITIC_PROFILE = "CRITIC_PROFILE"
    CRITIC_PROFILE_AMENDMENT = "CRITIC_PROFILE_AMENDMENT"


class ApprovalDecision(StrEnum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EDITED_AND_APPROVED = "EDITED_AND_APPROVED"
